apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 660119432667.dkr.ecr.us-east-1.amazonaws.com/netflix-backend:latest
          ports:
            - containerPort: 8080