apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  namespace: movie-app-ns
spec:
  selector:
    matchLabels:
      app: nginx-agent

  template:
    metadata:
      labels:
        app: nginx-agent
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80