apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: movie-app-ns

spec:
  type: ClusterIP
  selector:
    app: my-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80